### ISSUE TITLE
Allow setting weight for body

### ISSUE THREAD

**Issue by WickyNilliams** [KyleAMathews/typography.js#14]
Would be nice to be able to set body font-weight independently of headings. For example, Roboto 400 is quite heavy for a body font

**Comment by KyleAMathews** [comment]
Just to be clear, this issue (and #15) is for the website not the code? Because in the code this is already possible.

I definitely want to support this + some other more advanced features I've listed in other issues. I think there needs to be an advanced configuration area (perhaps in a modal) for less common settings like this. Pretty busy right now with startup stuff so PR definitely welcome if you're interested.

Also, completely unrelated, but I just saw you're the creator of headroom.js — I borrowed pretty heavily from your work recently to create https://github.com/KyleAMathews/react-headroom so thanks!

**Comment by WickyNilliams** [comment]
Yes, on the website sorry. Should have been more clear (aside: perhaps they should be split into two repos? Lib, and site consuming lib?).

I'll see if i can submit a PR, but ugh coffeescript :(

Don't know if you have a bad memory or I have a good one, but we've talked about Headroom on twitter. We even follow each other haha

**Comment by KyleAMathews** [comment]
[OMG, we did](https://twitter.com/WickyNilliams/status/570741936040120320_... but I didn't realize at the time you were the creator of headroom.js lol. I thought you were just some random React user who also wanted a react headroom component :D

**Comment by KyleAMathews** [comment]
But back on subject, yeah, splitting out the website could definitely make sense as they really can be used independently of each other. E.g. I showed this to my Mom recently who does a lot of graphic design and she said she'd love to use this tool instead of doing a lot of guess and check with font/typography.

**Comment by WickyNilliams** [comment]
Haha, I guess the lesson here is I need to work on being more clear in my writing :D 

Yes, that's exactly it. I'm not so interested in the lib (at the moment) as I am in just putting some nice typography together. I plan on building my website this/next week and would much prefer to let a tool do some of the heavy lifting, as CSS is horrible for that kind of thing of experimental (as you rightly point out in the README)

**Comment by KyleAMathews** [comment]
:D

Yeah, I hadn't intended the tool to be used at all this way — I built it mainly so I could stop using Sass/Compass and have a pure JS stack for handling styles in my React sites. But after building the website as a demo I realized that the outputted css is all many people would want (btw, you saw [this page right?](http://kyleamathews.github.io/typography.js/#/configuration)).

**Comment by KyleAMathews** [comment]
Also, did you see #10? I intend to incorporate pre-designed configurations like that somehow into the app.

**Comment by KyleAMathews** [comment]
Great typography should be a commodity not black magic you copy into your app and hope the incantation holds.

**Comment by WickyNilliams** [comment]
I did see (I actually went through every issue before opening a new one :), and I do intend to use the output CSS!

I think it's a great idea to have some good-to-go configurations.

**Comment by KyleAMathews** [comment]
Ok, just checking :)

Very excited to see what you come up with! Ping me when the site is up. Always fun to see a bit of your work make its way into the wild.

**Comment by KyleAMathews** [comment]
The new typography design tools support this.
