### ISSUE TITLE
Fairy Gates Theme: Messed up text shadow in default starter project header

### ISSUE THREAD

**Issue by tslaton** [KyleAMathews/typography.js#155]
This image shows what I see just following along with the tutorial (except I tried to use the `fairy-gates` theme instead of just `lawton` and `bootstrap` like the tutorial suggests). I don't see any issues with `lawton` or `bootstrap`.

<img width="841" alt="screen shot 2018-03-07 at 11 03 25 pm" src="https://user-images.githubusercontent.com/9665562/37137853-80347360-225c-11e8-9ef8-e33ef2c8477b.png">

**Comment by KyleAMathews** [comment]
Inspect the styles for the header. You'll need to remove I think some box-shadow.

**Comment by KyleAMathews** [comment]
Or override more likely is what you'll want to do.

**Comment by bushblade** [comment]
I am having this issue also, I can't override with inline styles, but why is the text shadow applied on this theme?

**Comment by matuella** [comment]
This theme applies both `text-shadow` and `background-image` probably because of the good appearance when some letters overlaps the background-image (the "underline"), but when [applying the styles](https://github.com/KyleAMathews/typography.js/blob/1a3bfc103d41d59f04e89573c2c87e1d95abdd12/packages/typography-theme-fairy-gates/src/index.js#L38), it "implies" that the background will be `#fff`, which I don't think it will be happening in most of the cases, and it's just my opinion.

If someone had any problem to change this, simply override `a` tag with:
```css
a {
  text-shadow: none;
  background-image: none;
}
```

**Comment by baerrach** [comment]
@matuella Where do I apply the override?
Most newbies (like me) just follow the tutorial and apply the theme and then wonder why its looking like that.

**Comment by baerrach** [comment]
@matuella Where do I apply the override?
Most newbies (like me) just follow the tutorial and apply the theme and then wonder why its looking like that.

**Comment by baerrach** [comment]
From https://kyleamathews.github.io/typography.js/ **Customizing themes**

```
fairyGateTheme.overrideThemeStyles = () => ({
  a: {
    textShadow: `none`,
    backgroundImage: `none`,
  },
});

const typography = new Typography(fairyGateTheme);
```

fixed the problem.
